# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

   
name: Demo Github Actions
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
          cache: maven
      - name: Give Permissions to mvnw
        run: chmod +x mvnw
      - name: Run All Test
        run: mvn verify
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
